apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lab2-yelp
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - kafka.yaml
  - user-service.yaml
  - owner-service.yaml
  - restaurant-service.yaml
  - review-service.yaml
  - review-worker.yaml
  - frontend.yaml
